key_name = "vsv"    # cahnge the keyname according to your requirement
instance_type = "t2.micro"   # cahnge the instancetype according to your requirement
region = "us-east-1"   # cahnge the region according to your requirement
bucket_name = "devops-assignment-time"
vpc-cidr    ="10.0.0.0/16"
pub-sub1-cidr ="10.0.1.0/24"
pub-sub2-cidr ="10.0.2.0/24"
pub-sub1-az ="us-east-1a"
pub-sub2-az ="us-east-1b"
pattoken = ""